# HiveMQ Challenge Response Authentication Extension

=== Purpose

The Challenge Response Authentication extension performs MQTT Client authentication
without direct exchange of credentials in post-registration sessions.

It has been added a further field “authMethod” to the authentication packet that specifies the type of authentication.
So a client authentication phase can be described as follow:
1) If a client is not registered, takes place a Simple Authentication where the broker saves the client credentials locally (hashed password)
2) If the client is already registered, takes place a Challenge-Response Authentication where the broker will send a challenge based on the client password

Tha authentication works as follow:
  1- Broker sends a long number powered by secure random numbers generator.
  2- Client encrypt it with AES by means of SHA-256 of its password as key and sends cipher text obtained to the broker.
  3- Broker compares the cipher text received from the client and that which has been computed from itself
  4- If they are equal then AUTHENTICATION SUCCESSFUL else AUTHENTICATION DENIED

=== Installation

. Clone this repository into a Java 11 maven project.
. Run `mvn package` goal from Maven to build the extension.
. Move the file: "target/HiveMQExtension-1.0.0-distribution.zip" to the directory: "HIVEMQ_HOME/extensions"
. Unzip the file.
. Start HiveMQ.
